config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.base_views.index, name='index'),
]

pybo/urls.py
"""
파일명 : urls.py
설 명 : pybo 모든 URL과 view함수의 mapping 담당
생성일 : 2023-01-25
생성자 : hamin
since 2023.01.09 Copyright (C) by Hamin All right reserved.
"""
from django.urls import path

from .views import base_views  # 현재디렉토리의 views 모듈
from .views import question_views
from .views import answer_views
# from pybo import views

app_name = 'pybo'

urlpatterns =[
    path('', base_views.index, name="index"),

    # temp menu
    # path("boot/menu/", views.boot_menu, name="boot_menu"),

    # answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name="answer_delete"),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name="answer_modify"),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name="answer_vote"),

    # question
    path('register/', question_views.register, name="register"),
    path('<int:question_id>/', question_views.detail, name="detail"),
    path('question/modify/<int:question_id>/', question_views.modify_question, name="question_modify"),
    path('question/delete/<int:question_id>/', question_views.delete_question, name="question_delete"),
    path('question/vote/<int:question_id>/', question_views.vote_question, name="question_vote"),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Question(models.Model):
    """질문 Question 클래스 생성: subject, content, create_date"""
    subject = models.CharField(max_length=200)  # 글자수 제한
    content = models.TextField()  # 글자수 제한이 없는 경우
    create_date = models.DateTimeField()
    # author 필드 추가: 글쓴이
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')  # 회원테이블에 사용자 정보가 삭제 되면 Question 테이블 user도 모두 삭제
    modify_date = models.DateTimeField(null=True, blank=True)
    # 데이터 베이스에서 null 허용, form.is_valid() 입력값 검증시 값이 없어도 된다. blank = True

    # 추천인
    voter = models.ManyToManyField(User, related_name='voter_question')
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()  # 글자수 제한이 없는 경우
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content

pybo/forms.py
"""
파일명 : forms.py
설 명 : 
생성일 : 2023-02-01
생성자 : hamin
since 2023.01.09 Copyright (C) by Hamin All right reserved.
"""

from django import forms
from pybo.models import Question, Answer


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer

        fields = ['content']

        labels = {
            'content': "답변 내용",
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용 할 question model

        fields = ['subject', 'content']  # QuestionForm에서 사용 할 question model의 속성

        # widgets = {  # 속성 추가: class rows 추가
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'cols': 30}),
        # }

        labels = {
            'subject': "제목",
            'content': "내용",
        }

pybo/views/answer_views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from pybo.forms import AnswerForm
from pybo.models import Question, Answer


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    logging.info('answer_vote 함수')
    answer = get_object_or_404(Answer, id=answer_id)

    if answer.author == request.user:
        messages.error(request, "자기 자신을 추천 할 수 없습니다.")
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.pk)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    logging.info('answer_delete에 잘 들어왔다')

    answer = get_object_or_404(Answer, pk=answer_id)

    if answer.author.username != request.user.username:
        messages.error(request, "권한이 없습니다.")
        return redirect('pybo:detail', question_id=answer.question.pk)

    answer.delete()
    return redirect('pybo:detail', question_id=answer.question.pk)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    logging.info("answer_modify에 잘 들어왔다")

    answer = get_object_or_404(Answer, pk=answer_id)

    if answer.author.username != request.user.username:
        messages.error(request, "권한이 없습니다.")
        return redirect('pybo:detail', question_id=answer.question.pk)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()

            answer.save()
            return redirect('pybo:detail', question_id=answer.question.pk)

    form = AnswerForm(instance=answer)
    context = {'form': form, 'question': answer.question}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_create(request, question_id):
    logging.info("answer_create question_id:{}".format(question_id))
    question = get_object_or_404(Question, pk=question_id)

    form = AnswerForm()
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user

            answer.save()  # 최종 저장
            # http://127.0.0.1:8000/pybo/500/#answer_46
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question.id), answer.pk))

    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/base_views.py
import logging

from django.core.paginator import Paginator
from django.shortcuts import render

from pybo.models import Question


def index(request):
    """ Question 목록 """
    logging.info("index 레벨로 출력")
    # list order create_date
    # Question.objects.order_by('create_date')  # ASC

    # 입력인자
    page = request.GET.get("page", '1')
    kw = request.GET.get("kw", '')
    s_type = request.GET.get("type", 'subject')
    rows = request.GET.get("rows", '10')
    logging.info("page:{}".format(page))
    logging.info("kw:{}".format(kw))

    question_list = Question.objects.order_by('-create_date')  # DESC order_by('-필드')
    # subject_container : 사용 __contains 또는 __icontains (대소 문자 구분)
    if s_type == "content":
        question_list = question_list.filter(content__contains=kw)
    elif s_type == "author":
        question_list = question_list.filter(author__username__contains=kw)
    else:
        question_list = question_list.filter(subject__contains=kw)

    paginator = Paginator(question_list, int(rows))
    page_obj = paginator.get_page(page)
    # paginator.count : 전체 개시물 개수
    # paginator.per_page : 페이지당 보여줄 게시물 개수
    # paginator.page_range : 페이지 범위
    # number: 현재 페이지 번호
    # previous_page_number: 이전 페이지 번호
    # next_page_number: 다음 페이지 번호
    # has_previous: 이전 페이지 유무
    # has_next: 다음 페이지 유무
    # start_index: 현재 페이지 시작 인덱스 (1부터 시작)
    # end_index: 현재 페이지 끝 인덱스

    context = {'question_list': page_obj, 'kw': kw, 'page': page, 'type': s_type, 'rows': int(rows)}
    logging.info('question_list:{}'.format(page_obj))

    return render(request, "pybo/question_list.html", context)

pybo/views/question_views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from pybo.forms import QuestionForm
from pybo.models import Question


@login_required(login_url='common:login')
def vote_question(request, question_id):
    logging.info('request.method : {}'.format(request.method))
    question = get_object_or_404(Question, id=question_id)

    # 본인 글은 본인이 추천 하지 못하게
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천 할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')  # 로그인이 되어있지 않으면 login 페이지로 이동
def register(request):
    """ 질문 등록 """

    logging.info('request.method : {}'.format(request.method))
    form = None
    if request.method == "POST":
        logging.info("question_create post")
        # 저장
        form = QuestionForm(request.POST)  # request.POST 데이터 (그냥 request는 GET이 default)
        if form.is_valid():  # form(질문 등록)이 유용하면
            question = form.save(commit=False)  # subject와 content만 저장 (DB에 물리적으로 commit은 하지 않음)
            question.create_date = timezone.now()
            question.author = request.user  # author 속성에 로그인 계정 저장
            logging.info('4. question.author: {}'.format(question.author))

            question.save()  # 날짜까지 생성해서 저장 (commit)
            return redirect("pybo:detail", question_id=question.id)
    else:
        form = QuestionForm()
    context = {'form': form, 'url': "{% url 'pybo:register' %}"}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def modify_question(request, question_id):
    logging.info("request.method: {}".format(request.method))
    context = None
    question = get_object_or_404(Question, id=question_id)
    if request.user.username != question.author.username:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question_id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()

            question.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
        context = {'form': form, 'url': ""}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def delete_question(request, question_id):
    logging.info("request.method: {}".format(request.method))
    question = get_object_or_404(Question, pk=question_id)

    if request.user.username != question.author.username:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question_id)

    question.delete()
    return redirect('index')

# def question_create(request):
#     question = Question(subject=request.POST.get("subject"),
#                         content=request.POST.get("content"),
#                         create_date=timezone.now())
#     question.save()
#     return redirect('pybo:detail', question_id=question.id)


def detail(request, question_id):
    """Question 상세"""
    logging.info(question_id)
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)

    if request.user != question.author:
        question.views += 1
        question.save()

    context = {'question': question, 'user': request.user}
    return render(request, "pybo/question_detail.html", context)

templates/pybo/answer_form.html
{% extends '../base.html' %}
{% block content %}
<main class="container">
    <form name="answer" action="" method="post" class="form-control">
        {% csrf_token %}
        <!-- form validation 기능 end -->
        {% include "form_errors.html" %}
        <!-- form validation 기능 end -->

        <textarea name="content" id="content" rows="5"
                  class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
        <input type="submit" value="답변등록" name="submit_answer" class="form-control">
    </form>
</main>
{% endblock %}

templates/pybo/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %} <!--css, js, images 로딩 최상단에 위치!-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!--  Bootstrap  -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>Title</title>
</head>
<body>
<!-- container start -->
<main class="container">
    <!-- 제목 -->
    <div class="text-start m-5">
        <h2>질문 목록</h2>
    </div>
    <!-- 제목 end -->

    <div class="d-grid gap-2 d-md-flex justify-content-end">
        <input type="button" class="btn btn-outline-secondary btn-sm" value="조회">
        <a href="#" class="btn btn-outline-primary btn-sm">등록</a>
    </div>

    <!-- 검색, 버튼 -->
    <div class="d-grid gap-2 d-md-flex justify-content-end mb-3">
        <form action="#" class="text-end input-group">
            <div class="col-sm-2 col-md-2 col-lg-2">
                <select class="form-select" aria-label="Default select example">
                    <option selected>전체</option>
                    <option value="10">제목</option>
                    <option value="20">내용</option>
                    <option value="30">작성자</option>
                </select>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <input type="text" class="form-control flex-2" placeholder="검색어 입력...">
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <select class="form-select flex-1" aria-label="Default select example">
                    <option selected>전체</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
            </div>
        </form>
    </div>
    <!-- 검색, 버튼 end -->
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr class="table-dark">
            <th scope="col" class="text-center">No.</th>
            <th scope="col" class="text-center">제목</th>
            <th scope="col" class="text-center">작성일</th>
            <th scope="col" class="text-center">조회수</th>
        </tr>
        </thead>
        <tbody>
        {% for question in question_list %}
        <tr>
            <td scope="col" class="text-center">{{question.id}}</td>
            <td scope="col" class="text-start">
                <a href="{% url 'pybo:detail' question.id %}">
                    {{question.subject}}
                </a>
            </td>
            <td scope="col" class="text-center">{{question.create_date|date:"Y-m-d"}}</td>
            <td scope="col" class="text-end">question.views</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</main>
<!-- table end -->
<!-- paging -->
<div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>
<!-- paging end -->
<!-- container end-->
</body>
</html>

templates/pybo/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a href="{% url 'pybo:index' %}" class="navbar-brand">Pybo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">fhrmdls</a>
            </li>
        </ul>
    </div>
</nav>

templates/pybo/question_detail.html
{% extends "../base.html" %}
{% load pybo_filter %}
{% block content %}
<main class="container">
    {% if question %}
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
        <strong>{{message.tags}}</strong>
        <ul>
            <li>{{message.message}}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- message 표시 end -->
    <h1>{{question.subject}}</h1>
    <strong class="d-flex justify-content-end">{{question.author.username}}</strong>
    <p>{{question.create_date|date:"Y년 m월 d일"}}</p>
    <div> 내용 :
        <p>
            {{question.content|mark}}
        </p>
    </div>
    <!-- 질문 수정 -->
    <div class="my-3">
        <a href="javascript:void(0);" class="recommend btn btn-outline-success"
           data-url="{% url 'pybo:question_vote' question.id %}">
            좋아요<span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
        </a>
        {% if request.user != None and question.author == request.user %}
        <a href="{% url 'pybo:question_modify' question.id %}" class="modify btn btn-outline-primary">수정</a>
        <a href="{% url 'pybo:question_delete' question.id %}" class="delete btn btn-outline-danger">삭제</a>
        <!--        <a href="javascript:void(0);" data-url="{% url 'pybo:question_delete' question.id %}"  -->
        <!--           class="delete btn btn-outline-danger">삭제</a>-->
        {% endif %}
    </div>

    <form name="answer" action="{% url 'pybo:answer_create' question.id %}" method="post" class="form-control">
        {% csrf_token %}
        <!-- form validation 기능 end -->
        {% include "form_errors.html" %}
        <!-- form validation 기능 end -->

        <textarea name="content" id="content" rows="5"
                  class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
        <input type="submit" value="답변등록" name="submit_answer" class="form-control">
    </form>
    <h3>답변: {{question.answer_set.count}}</h3>
    <div>
        <ul>
            {% for answer in question.answer_set.all %}
            <li>
                <!-- answer_+answer.id -->
                <a id="answer_{{answer.id}}"></a>
                <strong>{{answer.author.username}}</strong>  <!-- 글쓴이 -->
                <p>
                    {{answer.content}}
                </p>
                <a href="javascript:void(0);" class="recommend btn btn-outline-success"
                   data-url="{% url 'pybo:answer_vote' answer.id %}">
                    좋아요<span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user != None and answer.author == request.user %}
                <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-outline-primary">수정</a>
                <a href="{% url 'pybo:answer_delete' answer.id %}" class="btn btn-outline-danger">삭제</a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
    <p> 데이터가 소실 되었습니다 </p>
    {% endif %}
</main>
<script>
    const deleteBtn = document.querySelector(".delete")
    console.log("delete bebefore")

    if(deleteBtn != null){
        deleteBtn.addEventListener('click', function(e){
            if(confirm('삭제 하시겠습니까?')){
                console.log("delete")
                location.href = this.dataset["url"]
            } else {
                e.preventDefault()
            }
        });
    }

    const voteBtns = document.querySelectorAll(".recommend");
    console.log("vote bebefore")

    voteBtns.forEach(voteBtn => {
        voteBtn.addEventListener('click', function(e){
            console.log("vote before")
            if(confirm('투표 하시겠습니까?')){
                console.log("vote");
                location.href = this.dataset["url"];

            } else {
                e.preventDefault()
            }
        });
    });

</script>
{% endblock %}

templates/pybo/question_form.html
{% extends '../base.html' %}
{% block content %}
<main class="container">
    <div class="text-start mb-5">
        <h2>질문 등록</h2>
    </div>

    <form action="" method="post" class="">
        {% csrf_token %}
        <!-- form validation 기능 -->
        {% include "form_errors.html" %}

        <div class="mb-3">
            <label for="subject" class="col-form-label">제목</label>
            <div>
                <!--템플릿 필터-->
                <input type="text" class="form-control" id="subject" name="subject"
                       value="{{ form.subject.value|default_if_none:'' }}"
                >
            </div>
        </div>
        <div class="mb-3">
            <label for="content" class="col-form-label">내용</label>
            <div class="">
                <!-- content에 데이터가 없으면 None이라는 문자열이 표시 됨, None 대신 공백으로 표시하세요. -->
                <textarea name="content" id="content" rows="10" class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
        </div>

        <button type="submit" class="btn btn-outline-primary btn-sm">제출</button>
    </form>

</main>
{% endblock %}

templates/pybo/question_list.html
{% extends "../base.html" %}
{% load pybo_filter %} <!-- 사용자 정의 필터 로드 -->
{% block content%}
<!-- container start -->
<main class="container">
    <!-- 제목 -->
    <div class="text-start m-5">
        <h2>질문 목록</h2>
    </div>
    <!-- 제목 end -->

    <!-- 검색, 버튼 -->
    <div class="d-grid gap-2 d-md-flex justify-content-end mb-3">
        <div class="select-search">
            <select name="search-type" id="search-type">
                <option value="subject"
                        {% if type == "subject" %} selected {% endif %}>제목</option>
                <option value="content"
                        {% if type == "content" %} selected {% endif %}>내용</option>
                <option value="author"
                        {% if type == "author" %} selected {% endif %}>작성자</option>
            </select>
        </div>
        <div class="select-rows">
            <select name="rows-num" id="rows-num">
                <option value="10"
                        {% if rows == 10 %} selected {% endif %}>10줄</option>
                <option value="20"
                        {% if rows == 20 %} selected {% endif %}>20줄</option>
                <option value="30"
                        {% if rows == 30 %} selected {% endif %}>30줄</option>
            </select>
        </div>
        <div class="text-end my-1">
            <input type="text" name="search_kw" id="search_kw" value="{{ kw | default_if_none:'' }}"
                   class="form-control-sm">
        </div>

        <div class="col-sm-1 col-md-1 col-lg-1">
            <input type="button" class="btn btn-outline-secondary btn-sm" value="조회" id="btn_search">
            <a href="{% url 'pybo:register' %}" class="btn btn-outline-primary btn-sm">등록</a>
        </div>
    </div>
    <!-- 검색, 버튼 end -->
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr class="table-dark">
            <th scope="col" class="text-center">No.</th>
            <th scope="col" class="text-center" style="width: 50%;">제목</th>
            <th scope="col" class="text-center">작성일</th>
            <th scope="col" class="text-center">조회수</th>
            <th scope="col" class="text-center">작성자</th>
            <th scope="col" class="text-center">좋아요</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td scope="col" class="text-center">
                {{question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}
            </td>
            <td scope="col" class="text-start">
                <a href="{% url 'pybo:detail' question.id %}">
                    {{question.subject}}
                </a>
                {% if question.answer_set.count > 0 %} <!-- 답변이 있는 경우 -->
                <span class="text-danger small mx-2">{{question.answer_set.count}}</span>
                {% endif %}
            </td>
            <td scope="col" class="text-center">{{question.create_date|date:"Y-m-d"}}</td>
            <td scope="col" class="text-end">{{question.views}}</td>
            <td scope="col" class="text-end">{{question.author}}</td>
            <td scope="col" class="text-end">{{question.voter.count}}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">데이터가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- table end -->
    <!-- paging -->

    <!--페이징 처리 --------------------------- -->
    <ul class="pagination justify-content-center">
        <!--이전 페이지-->
        {% if question_list.has_previous %}
        <li class="page-item">
            <!--?page={{question_list.previous_page_number}}-->
            <a class="page-link" href="javascript:void(0);"
               data-page="{{question_list.previous_page_number}}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="javascript:void(0);" aria-disabled="true">&laquo;</a>
        </li>
        {% endif %}
        <!--이전 페이지 end-->

        <!--페이지 리스트-->
        {% for page_number in question_list.paginator.page_range %}
        <!--현재 선택 페이지와 나머지-->
        <!-- 페이지 번호가 현재 페이지 기준으로 좌우 5개씩 보이도록 처리-->
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5%}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{page_number}}"
               href="javascript:void(0);">{{page_number}}</a>
        </li>
        {% else %}
        <li class="page-item" aria-current="page">
            <a class="page-link" data-page="{{page_number}}"
               href="javascript:void(0);">{{page_number}}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!--페이지 리스트 end-->
        {% if question_list.has_next %}
        <li class="page-item">
            <!--?page={{question_list.next_page_number}}-->
            <a class="page-link" data-page="{{question_list.next_page_number}}"
               href="javascript:void(0);">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="javascript:void(0);" aria-disabled="true" tabindex="-1">&raquo;</a>
        </li>
        {% endif %}
        <!--다음 페이지-->
    </ul>
</main>
<form action="{% url 'index' %}" method="get" id="searchForm">
    <input type="hidden" name="kw" id="kw" value="{{ kw | default_if_none:''}}">
    <input type="hidden" name="page" id="page" value="{{ page }}">
    <input type="hidden" name="type" id="type" value="{{ type | default_if_none:'subject' }}">
    <input type="hidden" name="rows" id="rows" value="{{ rows | default_if_none:10 }}">
</form>
<!--페이지 처리 end --------------------------- -->

{% endblock %}

<!-- javascript -->
{% block script %}
<script>

    const page_links = document.getElementsByClassName("page-link");
    console.log(page_links);

    //btn-search : 검색어, page를 searchForm에 할당
    const btn_search = document.getElementById("btn_search");
    const search_kw = document.getElementById("search_kw");
    const kw = document.getElementById("kw");
    const page = document.getElementById("page");
    const searchType = document.getElementById("search-type");
    const type = document.getElementById("type");
    const search_form = document.forms["searchForm"];
    const rowsNum = document.getElementById("rows-num");
    const rows = document.getElementById("rows");

    function search(){
        kw.value = search_kw.value;
        page.value = 1;
        type.value = searchType.value;
        rows.value = rowsNum.value;
        search_form.submit();
    };

    search_kw.addEventListener('enter', ()=>{
        if (e.key === 'Enter') {
            search();
        }
    });

    Array.from(page_links).forEach(function(element){
        element.addEventListener('click', function(e){
            //console.log('page-link class');
            //console.log('this.dataset.page: '+this.dataset.page);
            kw.value = search_kw.value;
            page.value = this.dataset.page;
            rows.value = rowsNum.value;
            search_form.submit();
        });
    });

    btn_search.addEventListener('click', search);

</script>
{% endblock %}
<!-- javascript END -->

templates/pybo/question_list_back.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %} <!--css, js, images 로딩 최상단에 위치!-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!--  Bootstrap  -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>Title</title>
</head>
<body>
    <ul class="list-group">
        {# 한 줄 코멘트 #}
        <!--
            HTML 코멘트
            {와 % 사이에는 빈공간이 없어야 한다. {% (O), { % (X)
        -->
        {% comment %}
            <div>
                <p>불필요 블럭</p>
            </div>
        {% endcomment %}
        {% if question_list %}
            {% for question in question_list %}
                {# http://http://127.0.0.1:8000/pybo/1 #}
                <li class="list-group-item">
                    {{forloop.counter}},
                    {{forloop.counter0}},
                    <a href="{% url 'pybo:detail' question.id %}">{{question.subject}}</a>,
                    {{question.create_date|date:"Y-m-d"}}
                </li>
            {% endfor %}
        {% else  %}
            <p> 질문이 없습니다 </p>
        {% endif %}
    </ul>
    {% csrf_token %}
</body>
</html>