common/urls.py
"""
파일명 : urls.py
설 명 : 
생성일 : 2023-02-06
생성자 : hamin
since 2023.01.09 Copyright (C) by Hamin All right reserved.
"""
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    # django.contrib.auth 앱의 loginView 클래스를 활용
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='common/logout.html'), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.base_views.index, name='index'),
]

pybo/urls.py
"""
파일명 : urls.py
설 명 : pybo 모든 URL과 view함수의 mapping 담당
생성일 : 2023-01-25
생성자 : hamin
since 2023.01.09 Copyright (C) by Hamin All right reserved.
"""
from django.urls import path

from .views import base_views  # 현재디렉토리의 views 모듈
from .views import question_views
from .views import answer_views
# from pybo import views

app_name = 'pybo'

urlpatterns =[
    path('', base_views.index, name="index"),

    # temp menu
    # path("boot/menu/", views.boot_menu, name="boot_menu"),

    # answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name="answer_delete"),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name="answer_modify"),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name="answer_vote"),

    # question
    path('register/', question_views.register, name="register"),
    path('<int:question_id>/', question_views.detail, name="detail"),
    path('question/modify/<int:question_id>/', question_views.modify_question, name="question_modify"),
    path('question/delete/<int:question_id>/', question_views.delete_question, name="question_delete"),
    path('question/vote/<int:question_id>/', question_views.vote_question, name="question_vote"),
]

pybo/views/base_views.py
import logging

from django.core.paginator import Paginator
from django.shortcuts import render

from pybo.models import Question


def index(request):
    """ Question 목록 """
    logging.info("index 레벨로 출력")
    # list order create_date
    # Question.objects.order_by('create_date')  # ASC

    # 입력인자
    page = request.GET.get("page", '1')
    kw = request.GET.get("kw", '')
    s_type = request.GET.get("type", 'subject')
    rows = request.GET.get("rows", '10')
    logging.info("page:{}".format(page))
    logging.info("kw:{}".format(kw))

    question_list = Question.objects.order_by('-create_date')  # DESC order_by('-필드')
    # subject_container : 사용 __contains 또는 __icontains (대소 문자 구분)
    if s_type == "content":
        question_list = question_list.filter(content__contains=kw)
    elif s_type == "author":
        question_list = question_list.filter(author__username__contains=kw)
    else:
        question_list = question_list.filter(subject__contains=kw)

    paginator = Paginator(question_list, int(rows))
    page_obj = paginator.get_page(page)
    # paginator.count : 전체 개시물 개수
    # paginator.per_page : 페이지당 보여줄 게시물 개수
    # paginator.page_range : 페이지 범위
    # number: 현재 페이지 번호
    # previous_page_number: 이전 페이지 번호
    # next_page_number: 다음 페이지 번호
    # has_previous: 이전 페이지 유무
    # has_next: 다음 페이지 유무
    # start_index: 현재 페이지 시작 인덱스 (1부터 시작)
    # end_index: 현재 페이지 끝 인덱스

    context = {'question_list': page_obj, 'kw': kw, 'page': page, 'type': s_type, 'rows': int(rows)}
    logging.info('question_list:{}'.format(page_obj))

    return render(request, "pybo/question_list.html", context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="content=" width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %} <!--css, js, images 로딩 최상단에 위치!-->
    <!-- favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!--  Bootstrap  -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <script src="{% static 'bootstrap.min.js' %}" defer></script>

    <title>Title</title>
</head>
<body>
{% include './navbar.html' %}
{% block content %}
{% endblock %}
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
<!-- form validation 기능 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field in form %}
    {% if field.errors %}
    <div>
        <strong>{{field.label}}</strong>
    </div>
    {{field.errors}}
    {% endif %}
    {% endfor %}
</div>
{% endif %}
<!-- form validation 기능 end -->

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a href="{% url 'pybo:index' %}" class="navbar-brand">Pybo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %} <!-- 로그인 상태 -->
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="{% url 'common:logout' %}">
                        {{ user.username }} <i class="bi bi-box-arrow-left"></i>
                    </a>
                </li>
                {% else %} <!-- 로그아웃 상태 -->
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="{% url 'common:login' %}">
                        <i class="bi bi-box-arrow-in-right"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="{% url 'common:signup' %}">
                        회원가입
                    </a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="#">
                        <i class="bi bi-instagram"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>